### ISSUE TITLE
Добавить поддержку многоязычности для постов блога

### ISSUE THREAD

**Issue by ghost** [ailabitmo/ailabitmo.github.io#14]
Сейчас URL постов генерируются автоматически по стандартным правилам jekyll. Если кликнуть смену языка на странице с постом [1], то откроется несуществующая страница.
1. http://machine2-ailab.tk/ru//2015/02/02/2/

**Comment by KMax** [comment]
How to check file existence? Options:
- http://stackoverflow.com/questions/16528783/check-for-existence-of-file-using-jekyll
- https://github.com/michaelx/jekyll_file_exists

**Comment by ghost** [comment]
Для публикации, в front-matter поле `locale` надо заменить на `categories`, например, так:

``` yaml
---
layout: post
title: Лаборатория ISST присоединилась к финскому консорциуму "Интернет вещей"
published: true
categories: ru
---
```

`categories`, может, не очень красиво, но зато URL-ы генерируются стандартными средствами Jekyll (благодаря конфигу `permalink: /:categories/blog/:year/:month/:day/` в `config.yml`) — такой подход позволил избежать всяческих хитрых манипуляций с шаблонами, и в целом он хорошо встраивается в существующие костыли, что мы наделали.

P.S. Почему-то сайт не обновился, видимо, надо Jekyll перезапустить, я не знаю, где он находится. Локально у меня все работает корректно
